spring:
  datasource:
    url: jdbc:mysql://localhost:3306/donate?useUnicode=true&useSSL=false&characterEncodings=utf8&erverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: YYYY-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath*:/mapper/**Mapper.xml

server:
  port: 8080
